### ISSUE TITLE
Use commas in ltsp-dnsmasq.conf dns-server option

### ISSUE THREAD

**Issue by rkwesk** [ltsp/ltsp#28]
Please change all these:

https://github.com/ltsp/ltsp.github.io/blob/master/docs/ltsp-dnsmasq/index.html

```--dns-server=</strong><em>"space separated list"```

https://github.com/ltsp/ltsp/blob/master/docs/ltsp-dnsmasq.8.md

```-s, --dns-server="space separated list"```

In man ltsp-dnsmasq:

```-s, --dns-server="space separated list"
              Set the DNS server DHCP option. Defaults to autodetection. Proxy
              DHCP clients don´t receive DHCP options, so it´s recommended  to
              use  the ltsp.conf DNS_SERVER parameter when autodetection isn´t
              appropriate.
```
Here are all the relevent details (Ithink)

```root@ltsp19sonylap64:~# ltsp info
LTSP version: 19.09-1~201909140749~ubuntu18.04.1

SERVER XSESSIONS: lightdm-xsession.desktop  mate.desktop

SERVER OS: PRETTY_NAME="Debian GNU/Linux 10 (buster)"

CHROOTS:


VMs:


IMAGES:
x86_64
```
So I copy/paste to the root terminal:

```ltsp -o dnsmasq -d1 -p0 --dns-server="0.0.0.0 8.8.8.8 208.67.222.222"

root@ltsp19sonylap64:~# ltsp -o dnsmasq -d1 -p0 --dns-server="0.0.0.0 8.8.8.8 208.67.222.222"
Installed /usr/share/ltsp/server/dnsmasq/ltsp-dnsmasq.conf in /etc/dnsmasq.d/ltsp-dnsmasq.conf
Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
LTSP command failed: systemctl restart dnsmasq
Aborting ltsp
```
So let's see what's wrong:

```root@ltsp19sonylap64:~# systemctl status dnsmasq.service | tail -n20
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-09-15 09:40:35 EEST; 1min 0s ago
  Process: 7397 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
  Process: 7398 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=1/FAILURE)

Sep 15 09:40:35 ltsp19sonylap64 systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Sep 15 09:40:35 ltsp19sonylap64 dnsmasq[7397]: dnsmasq: syntax check OK.
Sep 15 09:40:35 ltsp19sonylap64 dnsmasq[7398]: dnsmasq: bad IPv4 address at line 33 of /etc/dnsmasq.d/ltsp-dnsmasq.conf
Sep 15 09:40:35 ltsp19sonylap64 systemd[1]: dnsmasq.service: Control process exited, code=exited, status=1/FAILURE
Sep 15 09:40:35 ltsp19sonylap64 dnsmasq[7398]: bad IPv4 address at line 33 of /etc/dnsmasq.d/ltsp-dnsmasq.conf
Sep 15 09:40:35 ltsp19sonylap64 systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Sep 15 09:40:35 ltsp19sonylap64 dnsmasq[7398]: FAILED to start up
Sep 15 09:40:35 ltsp19sonylap64 systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
```
Hold on a minute!! The system reports that the "syntax check" is ok but there is a "bad IPv4 address". Yes, I agree the address is bad BUT the syntax check should have picked up the error, no? Well I tried other ip's because that was how I interpreted the error message but I couldn't satisfy it because it hadn't occurred to me (for the longest time) that the white spaces were the problem.

line 33 of /etc/dnsmasq.d/ltsp-dnsmasq says

dhcp-option=option:dns-server,0.0.0.0 8.8.8.8 208.67.222.222

and I change it to

dhcp-option=option:dns-server,0.0.0.0,8.8.8.8,208.67.222.222

```root@ltsp19sonylap64:~# vi /etc/dnsmasq.d/ltsp-dnsmasq.conf 
root@ltsp19sonylap64:~# systemctl start dnsmasq.service
```
hurray! It works

```root@ltsp19sonylap64:~# systemctl status dnsmasq.service
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-09-15 09:52:19 EEST; 18s ago
  Process: 7538 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
  Process: 7539 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 7548 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
 Main PID: 7547 (dnsmasq)
    Tasks: 1 (limit: 2335)
   Memory: 1.0M
   CGroup: /system.slice/dnsmasq.service
           └─7547 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,

Sep 15 09:52:19 ltsp19sonylap64 dnsmasq[7547]: DNS service limited to local subnets
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq[7547]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq-dhcp[7547]: DHCP, IP range 192.168.67.20 -- 192.168.67.250, lease time 12h
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq-tftp[7547]: TFTP root is /srv/tftp
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq[7547]: reading /etc/resolv.conf
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq[7547]: using nameserver 192.168.1.1#53
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq[7547]: using nameserver 10.72.251.10#53
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq[7547]: using nameserver fe80::b167:ea72:3350:81b8%wlp6s0#53
Sep 15 09:52:19 ltsp19sonylap64 dnsmasq[7547]: read /etc/hosts - 5 addresses
Sep 15 09:52:19 ltsp19sonylap64 systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
```
Richard

**Comment by alkisg** [comment]
Hi Richard,

thanks for the bug report, it's a bug in the code, not in the documentation.
We do want the list to be space separated,
while then the code will properly put commas in the ltsp-dnsmasq.conf file.
That list is also used in the client resolv.conf, there's no reason to use commas like dnsmasq does.

I will commit a patch later on.

**Comment by rkwesk** [comment]
Ah, ok. What about the DNS_SERVER= variable that some may want to put in ltsp.conf?

Richard

**Comment by alkisg** [comment]
It's exactly the same, DNS_SERVER="space separated list".
And if one puts it under the [common] section, it affects both `ltsp dnsmasq` (i.e. no need to specify --dns-server there anymore) and the client resolv.conf.

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/7ab0f4a0ca698b5500b940966ce282bfe128e940.

**Comment by rkwesk** [comment]
I updated.

```root@ltsp19sonylap64:~# ltsp info
LTSP version: 19.09-1~201909151306~ubuntu18.04.1
```

I followed up as advised but dns-server still won't take whitespaces.

```root@ltsp19sonylap64:~# ltsp initrd
Generated ltsp.img:
-rw-r--r-- 1 root root 137216 Sep 17 04:55 /srv/tftp/ltsp/ltsp.img
root@ltsp19sonylap64:~# ltsp -o ipxe
/usr/sbin/ltsp: 95: /usr/sbin/ltsp: section_list: not found
Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipping existing /srv/tftp/ltsp/memtest.0
Skipping existing /srv/tftp/ltsp/memtest.efi
Skipping existing /srv/tftp/ltsp/snponly.efi
Skipping existing /srv/tftp/ltsp/undionly.kpxe
Installed iPXE binaries and configuration:
-rw-r--r-- 1 root root 2990 Sep 17 04:55 /srv/tftp/ltsp/ltsp.ipxe
-rw-r--r-- 1 root root 161968 Jul 24 13:10 /srv/tftp/ltsp/memtest.0
-rw-r--r-- 1 root root 1235864 Jul 24 13:10 /srv/tftp/ltsp/memtest.efi
-rw-r--r-- 1 root root 159296 Jul 24 13:10 /srv/tftp/ltsp/snponly.efi
-rw-r--r-- 1 root root 67642 Jul 24 13:10 /srv/tftp/ltsp/undionly.kpxe
root@ltsp19sonylap64:~# ltsp -o dnsmasq -d1 -p0 --dns-server="0.0.0.0 195.170.0.1 195.170.2.2"
Installed /usr/share/ltsp/server/dnsmasq/ltsp-dnsmasq.conf in /etc/dnsmasq.d/ltsp-dnsmasq.conf
Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
LTSP command failed: systemctl restart dnsmasq
Aborting ltsp
root@ltsp19sonylap64:~# ltsp -o dnsmasq -d1 -p0 --dns-server="0.0.0.0,195.170.0.1,195.170.2.2"
Installed /usr/share/ltsp/server/dnsmasq/ltsp-dnsmasq.conf in /etc/dnsmasq.d/ltsp-dnsmasq.conf
Restarted dnsmasq
root@ltsp19sonylap64:~# ltsp -o nfs
Installed /usr/share/ltsp/server/nfs/ltsp-nfs.exports in /etc/exports.d/ltsp-nfs.exports
Restarted nfs-kernel-server
```
Richard

**Comment by alkisg** [comment]
Hi Richard,

I committed the fix but I didn't send an update because this issue wasn't too important, so I was waiting for more commits.
Anyway I've just scheduled an update, it'll be ready in a few minutes.

I'm a bit worried about this error message of yours though:
`/usr/sbin/ltsp: 95: /usr/sbin/ltsp: section_list: not found`

Can you reinstall your ltsp.conf and run `ltsp -o ipxe` again and see if it goes away?
`man ltsp.conf` for instructions on how to install ltsp.conf.

**Comment by rkwesk** [comment]
Now that you explained that the d1 variable was enough for a local cache on the server and DNS=1 for the common section in ltsp.conf I understand that the issue is not pressing.

I am away from my test bed until the weekend but I have the same laptop using the wifi for the wan and have set the ethernet interface static 192.168.67.1. However, as I have nothing for the lan interface to connect to it remains down. Taking a closer look at my output as pasted above I realize that message happened on the partition with Debian whereas this time I have tried it with the ubuntu partition.

"I'm a bit worried about this error message of yours though:
/usr/sbin/ltsp: 95: /usr/sbin/ltsp: section_list: not found"

I was wondering about that but (at least on my ubuntu) this time it doesn't show:
```
root@ltsp19:~# !103
install -m 0660 /usr/share/ltsp/common/ltsp/ltsp.conf /etc/ltsp/.
root@ltsp19:~# ltsp -o ipxe
Installed /usr/share/ltsp/server/ipxe/ltsp.ipxe in /srv/tftp/ltsp/ltsp.ipxe
Skipping existing /srv/tftp/ltsp/memtest.0
Skipping existing /srv/tftp/ltsp/memtest.efi
Skipping existing /srv/tftp/ltsp/snponly.efi
Skipping existing /srv/tftp/ltsp/undionly.kpxe
Installed iPXE binaries and configuration:
-rw-r--r-- 1 root root 2990 Σεπ  19 14:38 /srv/tftp/ltsp/ltsp.ipxe
-rw-r--r-- 1 root root 161968 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.0
-rw-r--r-- 1 root root 1235864 Ιουλ 24 13:10 /srv/tftp/ltsp/memtest.efi
-rw-r--r-- 1 root root 159296 Ιουλ 24 13:10 /srv/tftp/ltsp/snponly.efi
-rw-r--r-- 1 root root 67642 Ιουλ 24 13:10 /srv/tftp/ltsp/undionly.kpxe
```
I will post this now and then reboot into Debian and see everything from there.

Richard

**Comment by rkwesk** [comment]
In Debian, after the last update there is no longer the message

"/usr/sbin/ltsp: 95: /usr/sbin/ltsp: section_list: not found" but as I reported in issue 31 under the same circumstances, i.e. first "ltsp initrd" is run and then "ltsp -o ipxe" there is the other message about resolve.service.

It may just be a coincidence (but I am very skeptical about coincedences!!) but I will keep investigating and when I return to where my test bed I will confirm that my Debian actually allows the client to work.

Richard

**Comment by rkwesk** [comment]
Yes, indeed the client logs in and has Internet access.

Richard
